services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - REAPER_HOST=${REAPER_HOST:-0.0.0.0}
      - REAPER_WEB_PORT=${REAPER_WEB_PORT:-8080}
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - reaper
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reaper-control-frontend
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://backend:3000}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - reaper
      - traefik
    depends_on:
      - backend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reaper-control.rule=Host(`reaper-control.test`)"
      - "traefik.http.routers.reaper-control.entrypoints=http"
      - "traefik.http.services.reaper-control.loadbalancer.server.port=5173"
      - "traefik.docker.network=traefik"

networks:
  reaper:
    driver: bridge
  traefik:
    external: true